version: '3.6'

networks:
  internet:
    name: "internet"
    driver: bridge

services:
  nats-server:
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-js"
    ports:
      - 4222:4222
      - 8222:8222
    image: nats:latest
    container_name: nats-server
    networks:
      - internet
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    restart: always

  consumer:
    volumes:
      - ./consumer:/app/consumer
    build: consumer/.
    networks:
      - internet
    tty: true
    depends_on:
      - nats-server

  publisher:
    volumes:
      - ./publisher:/app/publisher
    build: publisher/.
    networks:
      - internet
    tty: true
    ports:
      - 9000:9000
    depends_on:
      - nats-server
